apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: apatora/devops-test-api:latest
        name: devops-test-api
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: MONGO_HOST
          value: "mongo-mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          value: "root"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-mongodb
              key: mongodb-root-password
        - name: TEST
          value: test
        ports:
        - containerPort: 3000
        resources: {}
status: {}
